name: Terraform CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - "main"

permissions:
  contents: read
  id-token: write

jobs:
  pre-commit-checks:
    name: Pre-commit checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2
        with:
          fetch-depth: 0

      - name: Terraform min/max versions
        id: minMax
        uses: clowdhaus/terraform-min-max@v3.0.1

      - name: Pre-commit Terraform ${{ steps.minMax.outputs.maxVersion }}
        uses: clowdhaus/terraform-composite-actions/pre-commit@v1.14.0
        with:
          terraform-version: ${{ steps.minMax.outputs.maxVersion }}
          terraform-docs-version: v0.22.0

  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      statuses: write
    outputs:
      fmtOutcome: ${{ steps.fmt.outcome }}
      validateOutcome: ${{ steps.validate.outcome }}
      validateOutput: ${{ steps.validate.outputs.output }}
      checkovOutcome: ${{ steps.checkov.outcome }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2
        with:
          fetch-depth: 0

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4.0.0
        with:
          terraform_wrapper: false

      - name: Terraform Format
        id: fmt
        run: terraform fmt -list=true -check=true -recursive

      - name: Terraform Init
        id: init
        continue-on-error: true
        run: terraform init -backend=false

      - name: Terraform Validate
        id: validate
        continue-on-error: true
        run: |
          OUTPUT=$(terraform validate -no-color)

          echo $OUTPUT
          echo "output=$OUTPUT" >> $GITHUB_OUTPUT

      - name: Run Checkov
        id: checkov
        uses: bridgecrewio/checkov-action@v12.3101.0
        continue-on-error: true
        with:
          quiet: true

  comment-on-pr:
    needs: [lint]
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    permissions:
      contents: read
      pull-requests: write
      id-token: write
    steps:
      - name: PR Comment
        uses: actions/github-script@v6
        env:
          validateOutput: "${{ needs.lint.outputs.validateOutput }}"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fmtOutcome = "${{ needs.lint.outputs.fmtOutcome }}";
            const validateOutcome = "${{ needs.lint.outputs.validateOutcome }}";
            const checkovOutcome = "${{ needs.lint.outputs.checkovOutcome }}";

            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
            });

            const botComment = comments.find(comment => comment.user.type === 'Bot' && comment.body.includes('Terraform Validate Results'));

            const output = `#### Checkov Results 🛡️: \`${checkovOutcome}\`

            \n#### Terraform Fmt Check Results 🧹: \`${fmtOutcome}\`
            \n#### Terraform Validate Results 🤖 : \`${validateOutcome}\`
            <details><summary>Terraform Validate Output</summary>

            \`\`\`\n
            ${process.env.validateOutput}
            \`\`\`

            </details>`;

            if (botComment) {
              github.rest.issues.updateComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: botComment.id,
                body: output
              })
            } else {
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: output
              })
            }
